// <auto-generated />
namespace prjHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removesexoasrequiredforpersona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removesexoasrequiredforpersona));
        
        string IMigrationMetadata.Id
        {
            get { return "201903160240006_remove sexo as required for persona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
